# Generated by Django 3.2.4 on 2024-08-01 00:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flan',
            name='flan_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='flan',
            name='image_url',
            field=models.URLField(default='https://example.com/default_image.jpg'),
        ),
        migrations.AlterField(
            model_name='flan',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=64, unique=True),
        ),
    ]
