# Generated by Django 3.2.4 on 2024-08-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20240731_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='flan',
            name='price',
            field=models.IntegerField(default=2000),
        ),
    ]
