# Generated by Django 3.2.4 on 2024-08-07 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_flan_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='flan',
            name='offer',
            field=models.JSONField(default=[10, 15, 20, 25, 30, 35]),
        ),
    ]
