# Generated by Django 3.2.4 on 2024-08-07 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_flan_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='flan',
            name='actual_offer',
            field=models.IntegerField(default=20),
        ),
    ]
